### PR TITLE
corrected typo in match_points_to_graph.Rd

### PR DESCRIPTION
**Pull request by JimShady**

### CODE REVIEW

**Comment by mpadge** [comment]
Thanks for uncovering that glitch James - could you please also amend the description in the corresponding [source file](https://github.com/ATFutures/dodgr/blob/master/R/graph-functions-misc.R) used to generate that `.Rd` entry?

**Comment by JimShady** [comment]
Will do. I've not done many pull requests before so figured this was a good place/example to give one a go. 😁

**Comment by mpadge** [comment]
Like most R developers these days, I rely extensively on `devtools`. If you just change the entry in the original `R./*.R` file, then running `devtools::document(".")` will automatically update the corresponding `/man` entry.

**Comment by JimShady** [comment]
I think I have done that.

**Pull request merged**
